name: "$(managed_releasenumber)$(Rev:r)"
trigger: 
- none
pool:
  vmimage: 'windows-latest'
  name: 'DMC-Dev'

parameters:
  - name: saveziptorepo
    displayName: 'Save ZIP file to repo?'
    type: string
    values:
      - true
      - false
    default: false

variables:
- name: srcenv
  value: 'D365-Dmc-Dev'
- name: PowerPlatformSPN
- name: repobranch
  value: $(Build.SourceBranchName)
- name: repopath
  value: 'D365/CE/Solutions/SalesBase'
- name: repopathpacked
  value: 'D365/CE/Solutions/packed'
- name: ismanaged
  value: 'true'
- name: solutionname
  value: $(basesolutionname)
#
- name: artifactname
  value: $(solutionname)
- name: publish
- name: filepath
  value: '$(System.DefaultWorkingDirectory)\$(artifactname)\$(solutionname)_$(versionnumber).zip'
- group: OPGT 
- group: jts
stages:
- stage: Build_Deploy
  jobs:
    - job: Basic_Tasks
      condition: true
      steps:
      - checkout: self
        clean: true
        persistCredentials: true
      - template: basictask.yml
        parameters:
         srcenv: $(srcenv)

    - job: build_solution
      condition: true
      dependsOn: Basic_Tasks
      steps:
      - checkout: self
        clean: true
        persistCredentials: true

      - ${{ if eq(parameters.saveziptorepo, true) }}: 
          - template: powershell-clean.yml
            parameters:
              repobranch: $(repobranch)
              repopath: $(repopathpacked)
              solutionname: $(solutionname)
      - template: solutionbuild.yml
        parameters:
          srcenv: $(srcenv)
          ismanaged: '$(ismanaged)'
          solutionname: '$(solutionname)'
          artifactname: '$(artifactname)'

      - task: CopyFiles@2
        continueOnError: true
        inputs:
          SourceFolder: '$(Build.ArtifactStagingDirectory)'
          Contents: '$(solutionname)_$(versionnumber).zip'
          TargetFolder: '$(repopathpacked)'

      - ${{ if eq(parameters.saveziptorepo, true) }}: 
          - template: powershell-commit.yml
            parameters:
              repobranch: $(Build.SourceBranchName)
              repopath: $(repopathpacked)
              solutionname: $(solutionname)