name: "$(unmanaged_releasenumber)$(Rev:r)"
trigger: 
- none
#  branches:
#   exclude:
#     - opgt-dev
#  paths:
#    include:
#      - D365/CE/Settings/Opgt-Dev
#    exclude:
#      - D365/CE
pool:
  name: 'DMC-Dev'
  vmimage: 'windows-latest'

variables:
- group: OPGT 
- name: srcenv
  value: 'D365-Dmc-Dev'
- name: destenv
  value: 'D365-DMC-Qa'
- name: PowerPlatformSPN
- name: repobranch
  value: $(Build.SourceBranchName)
- name: repopath
  value: 'D365/CE/Solutions/SalesDependency'
- name: solutionname
  value: $(dependencyname)
- name: ismanaged
  value: 'False'
- name: artifactname
  value: $(solutionname)
- name: publish
- name: filepath
  value: '$(System.DefaultWorkingDirectory)\$(artifactname)\$(solutionname)_$(versionnumber).zip'

stages:
- stage: Build
  jobs:
    - deployment: 'SalesDependency_Unmanaged'
      environment: 'opgt'
    - job: Basic_Tasks
      condition: true
      steps:
      - checkout: self
        clean: true
        persistCredentials: true
      - template: basictask.yml
        parameters:
         srcenv: $(srcenv)

    - job: build_solution
      condition: true
      continueOnError: true
      dependsOn: Basic_Tasks
      steps:
      - checkout: self
        clean: true
        persistCredentials: true
      - template: solutionbuild.yml
        parameters:
          srcenv: $(srcenv)
          ismanaged: $(ismanaged)
          solutionname: '$(solutionname)'
          artifactname: '$(artifactname)'
      - template: powershell-clean.yml
        parameters:
          repobranch: $(repobranch)
          repopath: $(repopath)
          solutionname: $(solutionname)
      - task: PowerPlatformUnpackSolution@2
        displayName: 'Power Platform Unpack Solution '
        inputs:
          SolutionInputFile: '$(Build.ArtifactStagingDirectory)\$(solutionname)_$(versionnumber).zip'
          SolutionTargetFolder: $(repopath)
          SolutionType: unmanaged
      - template: powershell-commit.yml
        parameters:
          repobranch: $(repobranch)
          repopath: $(repopath)
          solutionname: $(solutionname)

    - job: test
      condition: true
      dependsOn: build_solution
      #needs: build_solution
      steps:
      - script: 
          echo "Service conn - $(PowerPlatformSPN)"
          echo "Service conn - ${{ variables.PowerPlatformSPN }}"

- stage: Deploy
  jobs:
    - job: Deploy
      condition: true
      steps:
      - template: deploy.yml
        parameters:
          destenv: $(destenv)
          ismanaged: $(ismanaged)
          publish: 'true'
          filepath: '$(System.DefaultWorkingDirectory)\$(artifactname)\$(solutionname)_$(versionnumber).zip'
          solutionname: $(solutionname)
          artifactname: $(artifactname)

    - job: Custom_Publish
      condition: true
      dependsOn: Deploy
      pool:
        vmimage: 'windows-latest'
      steps:
      - checkout: none
      - template: rulepublish.yml
        parameters:
          destenv: $(destenv)
          solutionname: '$(solutionname)'