name: "$(unmanaged_releasenumber)$(Rev:r)"
trigger: 
- none
#  branches:
#   exclude:
#     - opgt-dev
#  paths:
#    include:
#      - D365/CE/Settings/Opgt-Dev
#    exclude:
#      - D365/CE
pool:
  name: 'IST-CE-DEV-QA'
  vmimage: 'windows-latest'

variables:
- group: OPGT 
- name: srcenv
  value: 'D365-Jts-Dev2'
- name: destenv
  value: 'D365-Jts-DevQa'
- name: PowerPlatformSPN
- name: reponame
  value: $(Build.Repository.Name)
- name: commitmessage
  value: 'Sales_Base'
- name: repobranch
  value: $(Build.SourceBranchName)
- name: repopath
  value: 'D365/CE/Solutions/SalesBase'
- name: solutionname
  value: $(basesolutionname)
- name: ismanaged
  value: 'False'
- name: artifactname
  value: $(solutionname)
- name: publish
- name: filepath
  value: '$(System.DefaultWorkingDirectory)\$(artifactname)\$(solutionname)_$(versionnumber).zip'

stages:
- stage: Build
  jobs:
    - deployment: 'Base_Unmanaged'
      environment: 'opgt'
    - job: Basic_Tasks
      condition: true
      steps:
      - checkout: self
        clean: true
        persistCredentials: true
      - template: basictask.yml
        parameters:
         srcenv: $(srcenv)

    - job: build_solution
      continueOnError: true
      dependsOn: Basic_Tasks
      condition: succeeded()
      timeoutInMinutes: 80
      steps:
      - checkout: self
        clean: true
        persistCredentials: true
      - template: solutionbuild.yml
        parameters:
          srcenv: $(srcenv)
          ismanaged: $(ismanaged)
          solutionname: '$(solutionname)'
          artifactname: '$(artifactname)'
      - template: powershell-clean.yml
        parameters:
          repobranch: $(repobranch)
          repopath: $(repopath)
          solutionname: $(solutionname)
      - task: PowerPlatformUnpackSolution@2
        displayName: 'Power Platform Unpack Solution '
        inputs:
          SolutionInputFile: '$(Build.ArtifactStagingDirectory)\$(solutionname)_$(versionnumber).zip'
          SolutionTargetFolder: $(repopath)
          SolutionType: unmanaged
      - template: powershell-commit.yml
        parameters:
          reponame: $(Build.Repository.Name)
          repobranch: $(repobranch)
          repopath: $(repopath)
          commitmessage: '$(solutionname)-$(versionnumber)'
          
- stage: Test
  dependsOn: Build
  jobs:
    - job: test
      condition: true
      steps:
      - script: 
          echo "Service conn - $(PowerPlatformSPN)"
          echo "Test phase"

- stage: Deploy
  dependsOn: Build
  jobs:
    - job: Deploy
      condition: true
      timeoutInMinutes: 120
      steps:
      - template: deploy.yml
        parameters:
          destenv: $(destenv)
          ismanaged: $(ismanaged)
          publish: 'true'
          filepath: '$(System.DefaultWorkingDirectory)\$(artifactname)\$(solutionname)_$(versionnumber).zip'
          solutionname: $(solutionname)
          artifactname: $(artifactname)
          UseDeploymentSettingsFile: false
          DeploymentSettingsFile: 'No Settings'

    - job: Custom_Publish
      dependsOn: Deploy
      condition: succeeded()
      timeoutInMinutes: 30
      pool:
        vmimage: 'windows-latest'
      steps:
      - checkout: none
      - template: rulepublish.yml
        parameters:
          destenv: $(destenv)
          solutionname: '$(solutionname)'